### ISSUE TITLE
App Infrastructure, Layout & Styling

### ISSUE THREAD

**Issue by mliggs12** [mliggs12/personal-dashboard#48]
## TODO

- [ ] Authentication
  - [x] Handle route authorization - If user isn't authenticated, redirect to `/signin`
  - [x] Update Convex to deployment
- [ ] Component Libraries / Design Systems: basic UI elements, typography, spacing, and color systems - This is the foundation that remains to be built that will support any new feature
  - [ ] Final design in Figma
    - [ ] Global component/page styles
      - [ ] Tables
      - [ ] Add/Create `Doc` DialogDrawer button
    - [ ] Typography
      - Reference:
        - h1: bold 56px
        - h2: bold 48px
        - h3: bold 36px
        - h4: medium 32px
        - h5: medium 24px
        - h6: medium 20px
        - body-l: regular 18px
        - body-m: regular 16px
        - body-s: regular 14px
        - label-m: medium 16px
        - label-s: medium 14px
        - legend: regular 12px
    - [ ] Colors
    - [ ] Custom breakpoints: oversized, vertical
    - [ ] Dashboard layout
  - [x] Remove Top navbar
  - [x] Add Sidebar to all routes
- [ ] Refactor `utils.ts`
- [ ] [Progressive web app](https://nextjs.org/docs/app/building-your-application/configuring/progressive-web-apps)
