### ISSUE TITLE
Today's Tasks widget

### ISSUE THREAD

**Issue by mliggs12** [mliggs12/personal-dashboard#53]
## TODO

- [x] Add task to today button/input
  - [x] Fix remove due date
  - [x] Set input focus on open
- [x] Replace table with tasklist
- [x] Task detail modal
  - [x] Add property edits
- [x] Handle task completion
- [x] Fix add task inline layout shift
- [x] Change `due` to relative

## Notes

- https://blog.superhuman.com/content/images/2021/12/01_Personal-Dashboard-1.png
- Is it better to use multiple tasklists and Today List? As it stands, a task must have a due date to be displayed. What if I want to quickly record tasks that need to be done today, as they arise throughout the day? They would have to be assigned due as the current date. I think this is the best solution for now because technically they are due today and this avoids the need for position and dragging for now.
  - I could use status to set tasks todo today and return them to backlog at the end of the day. This way we can show tasks that don't have a deadline.
- I could use the add-task-inline which would allow me to create any task. I would just need to handle the UI shifts when it is opened.
