### ISSUE TITLE
tasks: add all basic task management functionality

### ISSUE THREAD

**Issue by mliggs12** [mliggs12/personal-dashboard#65]
### Tasks Page
- [ ] Multi-select functionality
  - [ ] Multi-select panel
- [ ] Columns
  - [ ] Created - format: 'Nov 1, 2025 3:38 PM'
  - Due date
- [ ] Update Name input
- [ ] Fix tasks table layout issue
- [ ] Update/customize logging
- [ ] Add better toasts for all functionality
### Recurring tasks
  - [ ] Fix monthly recurring on last/first day of month
    - [ ] Handle month scheduled task set on day that doesn't appear in the next month
  - [ ] Custom Schedule Month/Year Options dialog
    - Each
      - Calendar with Today selected and can select as many other days as desired
        - This is essentially the same for recur type By Specific Dates
      - Last Day selection
    - On the ...
      - First, Second, Third, Fourth, Fifth, Last
      - Sunday - Saturday
    - Workday
      - First workday
      - Last workday
  - [ ] Visual date selection calendar
  - [ ] Show recurrence count
  - [x] Fix multi weekly schedule calculations
    - I set a task to repeat every 2 weeks due on this Sunday the 14th, but the nextRunDate was set to the 21st instead of the 28th
  - [x] Handle updating/deletion of parent recurring task
    - Deleting a parent recurring task should delete all children instances
    - [x] Create Delete dialog like in G Calendar
  - [x] Show recurrence type on task items
  - [x] List all
  - [x] Review & test AI code / Refactor
    - [x] Combine recurring types logic
  - [x] bug: Task recreation doesn't carry over notes
  - [x] Handle priority from one instance to the next (since recurring tasks do not hold priority)
  - [x] Date & Repeat Dialog
### Tasks Card
- [ ] Subtasks
- [ ] 'Add Another Task' checkbox
- [ ] Layout shift when adding/removing first tag
- [x] refactor order/sort
## DONE
- [x] Update task due format from YYYY/MM/DD to standard YYYY-MM-DD
  - Recurring tasks are only saved to be a record of recurrences, so we need a new way to record so old tasks can be deleted
- [x] Update logic to incorporate Do Date and Due Date
  - [x] Tasks Card must be adjusted to accommodate
- [x] Handle old task cleanup/archiving with logging for recurring tasks
  - [x] Handle duplicate parent tasks
- [x] Status sort
- [x] Priority sort
- [x] Task Detail view
- [x] Update Status button
- [x] Update Priority button
- [x] Breadcrumbs
- [x] Update Deadline date picker
- [x] remove `due` if blank
- [x] Create Task dialog on dashboard close on creation
- [x] Refactor `tasks.ts`
