### ISSUE TITLE
Update Intention Details page

### ISSUE THREAD

**Issue by mliggs12** [mliggs12/personal-dashboard#68]
# TODO

- [x] Add statements select edit
  - Will need refactor
    - Edit text inputs: Update periodically or on submission?
    - Handle multiline text editing
  - Figure out how to remove styling on input focus
- [ ] Add 'x' delete button w/ confirmation dialog
- [x] Add Title select edit
- [ ] Add edit to Emotion select
  - [x] Remove/update the current toast
- [x] Remove focus outline for inputs
- [x] Show due dates for tasks
- [ ] Add ability to view task details page
- [ ] Show completed tasks at bottom of list (like in the todoist clone)
- [ ] Add resistance release functionality
  - "Why don't I have what I want yet?"
  - Record & release any bad-feeling thoughts/emotions that arise
  - Identify, record, and change limiting beliefs
- [ ] Add image set and/or generation
- [ ] Check updateAt functionality
  - [ ] Update Allow checking to only account for a status being updated to Allow
- [x] Update how text area for Notes changes to accommodate longer text
- [ ] Modal + Routing
  - Take time to research the correct implementation
- [ ] Update Status select
