### ISSUE TITLE
Session Tracker

### ISSUE THREAD

**Issue by mliggs12** [mliggs12/personal-dashboard#76]
## TODO

- [ ] Visible running state
- [ ] Cleanup/refactor timer logic
  - Works great but doesn't reset the timer upon completion
- [ ] Session Schedule View (see sub-issue)
- [ ] Tithe stats - the more % of my day is intentional, the better
  - Focus Hours by day/week/month
  - days accessed
  - day streak
- [x] Local state storage
  - I want to be able to retain and have access to the active session state
  - Insight: Maintain timer local state and save the current timer (Convex) if I navigate from the page.  This state would be recovered upon return to the page.
- [x] Add 'isRunning' state

## Problem statement, Solution requirements
  - Any tithing/focusing should be toward one's primary intentions and related tasks, therefore these options should be available when setting up a session.  Seek to work with what we are already creating instead of creating/tithing to random and/or sporadic subjects.  Choose what I want more and more.
  - This leads to an easy display of tithe/focus time toward each primary intention
  - See habits/patterns and the results of my work
  - Focus => Intention => Tasks

**Comment by mliggs12** [comment]
Merged tasks from duplicate issue
