### ISSUE TITLE
Google Calendar schedule view

### ISSUE THREAD

**Issue by mliggs12** [mliggs12/personal-dashboard#79]
What: This is key component underneath the higher processes and items (events, tasks, sessions).
- [Inspiration](https://imgix.setapp.com/app/428/screenshots/1688502431-64a4809f68751.png?auto=format%2Ccompress&dpr=1&ixlib=php-3.3.1&q=75&w=780), [2](https://imgix.setapp.com/app/428/screenshots/1688502430-64a4809e3a0cd.png?auto=format%2Ccompress&dpr=1&ixlib=php-3.3.1&q=75&w=780), [3](https://www.stayinsession.com/ipad-review.png), [4](https://www.stayinsession.com/hero.png), [AI convo](https://www.perplexity.ai/search/any-guides-or-tutorials-on-bui-WJlo2A4ITCefY_78F2wyxA), [GCal](https://calendar.google.com/calendar/u/0/r/agenda?pli=1), [Mobile](https://my.microsoftpersonalcontent.com/_api/v2.1/drives/d8c219843179be3d/items/D8C219843179BE3D!sea28faa254284116a6d5aa3f224cf583/thumbnails/0/c451x966/content?prefer=noredirect%2Cclosestavailablesize&cb=2024-10-26T19%3A13%3A50Z&eh=Scenario%3AOneUp), [example](https://github.com/SwitchbackTech/compass?ref=reactjsexample.com)
- Track, record, display primary intentions and their tithe statistics, tasks, progress to possibly gleam insights or appreciate work

Why: Displays the commitments of the mundane day and allows me to interact with the schedule as needed.
- Important tool in supporting the dance between the needs of the mundane (productivity) and the desire to create freely.
- Work with the flow and timing of the mundane needs (i.e. circadian rhythm); record, display, chart, analyze

## TODO

- [ ] Clarify MVP structure from first principles extending outward
- [ ] Calendar view
  - [ ] Header
    - Date
    - Summary/Statistics
    - Day Tabs (for later, start by only showing today)
      - the view has infinite scroll but tabs can be used to scroll the designated day into view
      - defaults to the start of the current hour of today (with some space above)
    - Today button
  - [ ] Event Block
    - Title
    - Start time OR Start time - End time
    - Duration (minutes)
  - [ ] Event Details Dialog
  - [ ] Grid
    - Review Grid and other [components](https://github.com/SwitchbackTech/compass/tree/main/packages/web/src/views/Calendar/components)
  - [ ] Now Line
  - [ ] Add Event Button
- [ ] Timeline view
